### ISSUE TITLE
依赖的carbon@V1.5.5没有了

### ISSUE THREAD

**Issue by zhoushun5678** [ArtisanCloud/PowerLibs#105]
github.com/golang-module/carbon v1.5.5
这个包没有了，能兼容下吗

**Comment by Matrix-X** [comment]
是要兼容carbon v2么

**Comment by zhoushun5678** [comment]
不需要的，我现在的问题是这个carbon拉不下来，报错了

**Comment by Matrix-X** [comment]
拉不下来应该是源或者网络问题？
截图看看

**Comment by zhoushun5678** [comment]
图片不知道为啥传不了。goland提示这个：go: github.com/golang-module/carbon@v1.5.5: invalid version: unknown revision v1.5.5

**Comment by Matrix-X** [comment]
你还是加我微信吧，hbj418
