### ISSUE TITLE
json序列化&转为\u0026 微信不接受这中参数

### ISSUE THREAD

**Issue by danbai225** [ArtisanCloud/PowerLibs#81]
![image](https://github.com/ArtisanCloud/PowerLibs/assets/40517872/63d5cb9e-25ca-4497-afc7-7ba87af0b1a1)

建议添加   encoder.SetEscapeHTML(false)

或者作为一种开关 不然有的接口传不进去

**Comment by Matrix-X** [comment]
pls check
PowerLib v3.0.15
PowerWechat v3.1.3, 

refact(http): add SetEscapeHTML false
